services:
  api:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    environment:
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: snippet-db
      DB_HOST: db
      DB_PORT: 5432

  db:
    container_name: snippet-db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: snippet-db
    volumes:
      - pgdata:/var/lib/postgresql/data #para guardar de forma persistente
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  pgdata:

spring:
  redis:
    host: redis
    port: 6379