spring:
  application:
    name: snippet-searcher-app
  #datasource:
  #  url: jdbc:postgresql://snippet-db:5432/snippet-db
  #  username: sa
  #  password: password
  #jpa:
  #  hibernate:
  #    ddl-auto: update
  #  show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-65tlgyzfpbzeka8a.us.auth0.com/
  redis:
    host: redis
    port: 6379
redis:
  stream:
    key: "jobs"

app:
  accessmanager:
    url: http://${ACCESS_MANAGER_HOST}:${ACCESS_MANAGER_PORT}

server:
  port: 8080

# Configuración JWT local (puedes mantenerla si también usas JWT propio)
#jwt:
#  secret: tu-super-secreto-jwt-key-minimo-256-bits
#  expiration: 86400000 # 24 horas en ms

# Configuración Auth0
auth0:
  domain: dev-65tlgyzfpbzeka8a.us.auth0.com
  audience: https://api.snippets.com
  clientId: WlTG30qceM7qOiDY0hB90bVtUog4xCdp
  clientSecret: gR_X5kVh5bjLPwqh9IHLE2aSwKFu5pkQ-MoIaN8Yjk_NIsAWbonq47IpgyoPjzPX


# Configuración de logs con request-id
logging:
  pattern:
    console: "[%X{request_id}] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO
    com.grupo14IngSis.snippetSearcher: DEBUG
